<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{{ config('app.name', 'Philcst') }}</title>

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.bunny.net">
    <link href="https://fonts.bunny.net/css?family=instrument-sans:400,500,600" rel="stylesheet" />

    <!-- Styles / Scripts -->
    @if (file_exists(public_path('build/manifest.json')) || file_exists(public_path('hot')))
        @vite(['resources/css/app.css', 'resources/js/app.js'])
    @else
        <style>
            /*! tailwindcss v4.0.7 | MIT License | https://tailwindcss.com */
            /* Leave this exactly as generated by Laravel */
        </style>
    @endif

    @livewireStyles

    <style>
        /* Completely hide any Livewire/NProgress progress bar */
        #nprogress,
        #nprogress .bar,
        #nprogress .peg,
        #nprogress .spinner,
        #livewire-progress-bar,
        .livewire-progress-bar,
        livewire-progress-bar,
        [data-navigate-progress-bar],
        [wire\:navigate-progress] {
            display: none !important;
            opacity: 0 !important;
            visibility: hidden !important;
            height: 0 !important;
            width: 0 !important;
            pointer-events: none !important;
        }
    </style>
</head>

<body>

    {{ $slot }}

    @livewireScripts

    <script>
        // Kill any progress bar after page load
        document.addEventListener('DOMContentLoaded', () => {
            const removeBar = () => {
                document.querySelectorAll(
                    '#nprogress, .livewire-progress-bar, #livewire-progress-bar, [data-navigate-progress-bar]'
                ).forEach(el => el.remove());
            };

            removeBar();

            const observer = new MutationObserver(removeBar);
            observer.observe(document.body, {
                childList: true,
                subtree: true
            });
        });
    </script>

</body>
</html>